# Generated by Django 5.1.1 on 2024-09-23 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reader", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="passengeruser",
            name="profile_picture",
        ),
    ]
