# Generated by Django 5.1.1 on 2024-09-23 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reader", "0002_remove_passengeruser_profile_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cardinfo",
            name="subscription_type",
        ),
    ]
