# Generated by Django 5.1.1 on 2024-09-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader", "0003_remove_cardinfo_subscription_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardassignmentid",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_in_circulation", "Not in Circulation"),
                    ("assigned", "Assigned"),
                    ("available", "Available"),
                ],
                default="not_in_circulation",
                help_text="The card status (Not in Circulation, Assigned, or Available).",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="cardassignmentid",
            name="unique_code",
            field=models.CharField(
                help_text="The unique card assignment number for each user.",
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="cardassignmentid",
            name="user_type",
            field=models.CharField(
                choices=[("P", "Parent"), ("E", "Employee"), ("S", "Student")],
                default="S",
                help_text="The type of user: Parent, Employee, or Student.",
                max_length=1,
            ),
        ),
    ]
